name: test 
on: push
jobs: 
  log-date: 
    runs-on: ubuntu-latest
    steps:
      - name: create date
        run: date >> date.txt
      - name: read date
        run: cat date.txt
  log-node-version:
    needs: log-date
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: node --version   
      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24
    steps:
      - name: log node version
        run: node --version
  log-readme:
    runs-on: ubuntu-latest
    steps:
      - name: checout repo
        uses: actions/checkout@v5
      - name: log readme.md
        run: cat README.md